const imagesSeq = [
  "afternoon_street",
  "amsterdam",
  "annie-spratt",
  "asian_nite",
  "boxed-water-is-better-2",
  "boxed-water-is-better-3",
  "boxed-water-is-better",
  "canyon",
  "cave_cupula",
  "erol-ahmed",
  "euro_beach",
  "fatih-kgqu",
  "fer-nando",
  "gordo_s3t",
  "holand_pigeon",
  "ian-dooley",
  "jay-antol",
  "jean-philippe",
  "jj-ying-7JX0",
  "john-mccann",
  "kees-streefkerk",
  "kyle-johnson",
  "mountains",
  "night_windows",
  "old_italian_car",
  "orange_balcony",
  "orange_building",
  "orange_windows",
  "patrick-tomasso",
  "pawel-czerwinski",
  "pawel-czerwinski2",
  "purple_bubbles",
  "ray-mallick",
  "robin-schreiner",
  "saad-chaudhry",
  "sanjeevan-satheeskumar",
  "tom-barrett",
  "victorian",
  "windows",
  "afternoon_street",
  "amsterdam",
  "annie-spratt",
  "asian_nite",
  "boxed-water-is-better-2",
  "boxed-water-is-better-3",
  "boxed-water-is-better",
  "canyon",
  "cave_cupula",
  "erol-ahmed",
  "euro_beach",
  "fatih-kgqu",
  "fer-nando",
  "gordo_s3t",
  "holand_pigeon",
  "ian-dooley",
  "jay-antol",
  "jean-philippe",
  "jj-ying-7JX0",
  "john-mccann",
  "kees-streefkerk",
  "kyle-johnson",
  "mountains",
  "night_windows",
  "old_italian_car",
  "orange_balcony",
  "orange_building",
  "orange_windows",
  "patrick-tomasso",
  "pawel-czerwinski",
  "pawel-czerwinski2",
  "purple_bubbles",
  "ray-mallick",
  "robin-schreiner",
  "saad-chaudhry",
  "sanjeevan-satheeskumar",
  "tom-barrett",
  "victorian",
  "windows",
].map((img) => ({
  img_url: `images/01.${img}_2400X1350.jpg`,
  mini_img_url: `images/01.${img}_36X20.jpg`,
}));

const images = [];
let i = 0;
while (i < 2) {
  images.push(...imagesSeq);
  i++;
}
export { images };
